-- Add sample pages to the database
USE astro_forge_db;

-- Clear existing pages and insert sample data
DELETE FROM pages;

INSERT INTO pages (title, slug, content, meta_description, is_published, display_order) VALUES
('About Us', 'about', 
'[{"type":"text","title":"Company Overview","content":"Astro Forge Holdings is a leading provider of innovative solutions across multiple industries including mining, real estate, agriculture, and community development. Founded with a vision to create sustainable impact across Africa, we combine cutting-edge technology with deep industry expertise to deliver transformative results.","order":1,"is_active":true},{"type":"text","title":"Our Mission","content":"Our mission is to build tomorrow\'s infrastructure through innovation, sustainability, and strategic investment. We are committed to creating lasting positive impact in the communities we serve while delivering exceptional value to our stakeholders.","order":2,"is_active":true},{"type":"text","title":"Our Values","content":"• Innovation: We embrace new technologies and creative solutions\\n• Sustainability: We prioritize environmental responsibility\\n• Community: We invest in local communities and their development\\n• Excellence: We maintain the highest standards in everything we do\\n• Integrity: We operate with transparency and ethical practices","order":3,"is_active":true}]',
'Learn about Astro Forge Holdings, our mission, values, and commitment to sustainable development across Africa.',
TRUE, 1),

('Contact Information', 'contact', 
'[{"type":"text","title":"Get In Touch","content":"We\'re here to help you bring your vision to life. Whether you\'re looking to start a new project, explore partnership opportunities, or simply learn more about our services, our team is ready to assist you.","order":1,"is_active":true},{"type":"text","title":"Contact Details","content":"📧 Email: info@astroforge.com\\n📞 Phone: +1 (555) 123-4567\\n📍 Address: 123 Business Plaza, Innovation District, Tech City, TC 12345\\n🕒 Hours: Monday - Friday: 9:00 AM - 6:00 PM","order":2,"is_active":true},{"type":"text","title":"Business Hours","content":"Our team is available during standard business hours to assist with your inquiries and project needs. For urgent matters outside of business hours, please leave a message and we\'ll respond as soon as possible.","order":3,"is_active":true}]',
'Contact Astro Forge Holdings for project inquiries, partnerships, or general information. We\'re here to help bring your vision to life.',
TRUE, 2),

('Privacy Policy', 'privacy', 
'[{"type":"text","title":"Privacy Policy","content":"At Astro Forge Holdings, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, and safeguard your data when you visit our website or use our services.","order":1,"is_active":true},{"type":"text","title":"Information We Collect","content":"We may collect personal information such as your name, email address, phone number, and company details when you contact us, subscribe to our newsletter, or use our services. We also collect technical information about your device and browsing activity.","order":2,"is_active":true},{"type":"text","title":"How We Use Your Information","content":"We use the information we collect to:\\n• Provide and improve our services\\n• Communicate with you about projects and updates\\n• Send newsletters and marketing materials (with your consent)\\n• Comply with legal obligations\\n• Protect our rights and prevent fraud","order":3,"is_active":true},{"type":"text","title":"Data Security","content":"We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. Your data is stored securely and accessed only by authorized personnel.","order":4,"is_active":true}]',
'Learn about how Astro Forge Holdings protects your privacy and handles your personal information.',
TRUE, 3),

('Terms of Service', 'terms', 
'[{"type":"text","title":"Terms of Service","content":"These Terms of Service govern your use of Astro Forge Holdings website and services. By accessing or using our services, you agree to be bound by these terms and our Privacy Policy.","order":1,"is_active":true},{"type":"text","title":"Acceptance of Terms","content":"By using our website or services, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.","order":2,"is_active":true},{"type":"text","title":"Use of Services","content":"You may use our services for lawful purposes only. You agree not to:\\n• Use our services for any illegal or unauthorized purpose\\n• Interfere with or disrupt our services or servers\\n• Attempt to gain unauthorized access to our systems\\n• Use our services to transmit harmful or malicious content","order":3,"is_active":true},{"type":"text","title":"Intellectual Property","content":"All content on our website, including text, graphics, logos, and software, is the property of Astro Forge Holdings and is protected by copyright and other intellectual property laws. You may not reproduce, distribute, or create derivative works without our written permission.","order":4,"is_active":true}]',
'Read our Terms of Service to understand the rules and guidelines for using Astro Forge Holdings website and services.',
TRUE, 4),

('Careers', 'careers', 
'[{"type":"text","title":"Join Our Team","content":"At Astro Forge Holdings, we\'re always looking for talented individuals who share our passion for innovation and sustainable development. Join our team and help us build a better future across Africa.","order":1,"is_active":true},{"type":"text","title":"Current Openings","content":"We currently have opportunities in the following areas:\\n• Project Management\\n• Engineering (Mining, Civil, Agricultural)\\n• Technology Development\\n• Business Development\\n• Community Relations\\n• Environmental Science","order":2,"is_active":true},{"type":"text","title":"Benefits","content":"We offer competitive benefits including:\\n• Health and wellness programs\\n• Professional development opportunities\\n• Flexible work arrangements\\n• Competitive compensation\\n• Travel opportunities across Africa\\n• Impact-driven work environment","order":3,"is_active":true},{"type":"text","title":"How to Apply","content":"To apply for a position, please send your resume and cover letter to careers@astroforge.com. Include the position title in your subject line and tell us why you\'d be a great fit for our team.","order":4,"is_active":true}]',
'Explore career opportunities at Astro Forge Holdings. Join our team of innovators and make a difference across Africa.',
TRUE, 5),

('FAQ', 'faq', 
'[{"type":"text","title":"Frequently Asked Questions","content":"Find answers to common questions about Astro Forge Holdings, our services, and how we can help with your projects.","order":1,"is_active":true},{"type":"text","title":"What services does Astro Forge offer?","content":"We offer comprehensive solutions across multiple industries including mining operations, real estate development, agricultural technology, community development, and educational programs. Each service is tailored to meet the specific needs of our clients and communities.","order":2,"is_active":true},{"type":"text","title":"How do I get started with a project?","content":"Getting started is easy! Simply contact us through our website, email, or phone. Our team will schedule a consultation to discuss your project requirements, timeline, and budget. We\'ll then develop a customized proposal for your review.","order":3,"is_active":true},{"type":"text","title":"Do you work internationally?","content":"Yes, we primarily focus on projects across Africa, working with local communities, governments, and international partners. Our expertise spans multiple countries and we have experience navigating various regulatory environments.","order":4,"is_active":true},{"type":"text","title":"What makes Astro Forge different?","content":"We combine deep industry expertise with innovative technology and a strong commitment to sustainability and community impact. Our approach focuses on creating lasting positive change while delivering exceptional results for our clients.","order":5,"is_active":true}]',
'Find answers to frequently asked questions about Astro Forge Holdings services, projects, and how we can help you.',
TRUE, 6);

-- Verify the pages were created
SELECT id, title, slug, is_published, display_order, created_at FROM pages ORDER BY display_order; 